AmanClothHouse/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^garments/', include('garments.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

garments/urls.py
from django.conf.urls import url
from . import views

app_name = 'garments'

urlpatterns = [
    #/garments/
    url(r'^$', views.index, name = 'index'),
    #/garments/contact_us/
    url(r'^contact_us/$', views.Contact_us_View.as_view(), name='contact_us'),
    #/garments/about_us/
    url(r'^about_us/$', views.About_us_View.as_view(), name='about_us'),
    #/garments/gallery/men/
    url(r'^gallery/men/$', views.gallery_men, name='gallery men'),
    #/garments/gallery/women/
    url(r'^gallery/women/$', views.gallery_women, name='gallery women'),

    url(r'^(?P<product_id>[0-9]+)/view_details/$', views.detail, name='detail'),
]

garments/models.py
from django.db import models


class product(models.Model):
    product_name = models.CharField(max_length=300)
    product_details = models.CharField(max_length=500)
    product_image = models.FileField()
    product_price = models.CharField(max_length=100)
    gender = models.CharField(max_length=20)

garments/views.py
from django.views import generic
from .models import product
from django.shortcuts import render
from django.views.generic import TemplateView

def index(request):
    all_garments = product.objects.all()
    garments_men = []
    garments_women = []
    for garment in all_garments:
        if(garment.gender == "Men"):
            garments_men.append(garment)
        else:
            garments_women.append(garment)
    return render(request, 'garments/index.html', {'garments_men': garments_men,'garments_women': garments_women})

# class IndexView(generic.TemplateView):
#     template_name = 'garments/index.html'


class Contact_us_View(TemplateView):
    template_name = 'garments/contact_us.html'



class About_us_View(TemplateView):
    template_name = 'garments/about_us.html'

def gallery_men(request):
    all_garments = product.objects.all()
    garments_men = []

    for garment in all_garments:
        if(garment.gender == "Men"):
            garments_men.append(garment)

    return render(request, 'garments/gallery.html', {'all_garments': garments_men})

def gallery_women(request):
    all_garments = product.objects.all()
    garments_women = []

    for garment in all_garments:
        if (garment.gender == "Women"):
            garments_women.append(garment)

    return render(request, 'garments/gallery.html', {'all_garments': garments_women})

def detail(request,product_id):
    garment_details = product.objects.get(pk=product_id)

    return render(request, 'garments/detail.html', {'all_garments': garment_details})

templates/garments/about_us.html
{% extends 'garments/base.html' %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>{% block title %}About_Us{% endblock %}</title>
</head>
<body>
{% block body %}
    <div class="container-fluid">
        <div style="color: deepskyblue" class="text-center">
            <h2>About Us</h2>
            <div style="color: whitesmoke; padding-right: 150px; padding-left: 150px" class="text-center">

                <p><h4>Aman Cloth House is the fun, friendly spot for style and decor that's as
                expressive and unique as you are!We carry a curated selection of styles from
                hundreds of independent designers.We listen to our community and put them at
                the center of everything we do.Giving you plenty of opportunities to have
                your voice heard is what Aman Cloth House fresh,relevant,and growing by leaps
                and bounds! Karan Garments is the branch of Aman Cloth House. A cool spot to buy
                trendy branded clothes.
               </h4>

                </p>

            </div>
            <hr class="separator" style="color: aquamarine">
            <h2>Meet Our Leaders</h2>

        </div>
        <div class="row">
            <div class="col-md-6">
                <img src="{% static "garments/images/papa.jpg" %}" class="img-responsive img-circle center-block">
                <div class="text-center" style="color: whitesmoke">
                    <h4>Harvinder Singh Sodhi</h4>
                </div>

            </div>
            <div class="col-md-6">
                <img src="{% static "garments/images/kannu.jpg" %}" class="img-responsive img-circle center-block">
                <div class="text-center" style="color: whitesmoke">
                    <h4>Arsh Kanwal Sodhi</h4>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

</body>

templates/garments/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}AmanClothHouse{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href= {% static "garments/style.css"  %} />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <div id="map-canvas"></div>
    <script type='text/javascript' src="http://maps.googleapis.com/maps/api/js?sensor=false&extension=.js&output=embed"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button"class="navbar-toggle"  data-toggle="collapse" data-target="#topnavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'garments:index' %}" >AmanClothHouse</a>
        </div>
        <div class="collapse navbar-collapse" id="topnavbar">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="{% url "garments:index" %}" class="dropdown-toggle"data-toggle="dropdown">
                        <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>&nbsp;Gallery<span class="caret"></span>
                        <ul class="dropdown-menu">
                            <li><a href="{% url "garments:gallery men" %}">Men</a></li>
                            <li><a href="{% url "garments:gallery women" %}">Women</a></li>
                        </ul>

                    </a>
                </li>
                <li class="">
                    <a href="{% url "garments:about_us" %}">
                        <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp;About Us

                    </a>
                </li>
                <li class="">
                    <a href="{% url "garments:contact_us" %}">
                        <span class="glyphicon glyphicon-phone" aria-hidden="true"></span>&nbsp;Contact Us

                    </a>
                </li>
            </ul>
        </div>
        </div>

</nav>
{% block body %}
{% endblock %}

</body>
</html>

templates/garments/contact_us.html
{% extends 'garments/base.html' %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Contact_Us{% endblock %}</title>
    <style>
        #map {
            height: 400px;
            width: 100%;
        }
    </style>
</head>
<body>
{% block body %}
    <div class="container-fluid">
        <div id="map"></div>
        <script>
            function initMap() {
                {% comment %}29.949441,73.619106{% endcomment %}
                var uluru = {lat: 29.949441, lng: 73.619106};
                var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 10,
                    center: uluru
                });
                var marker = new google.maps.Marker({
                    position: uluru,
                    map: map
                });


            }
        </script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAifGMAWqbZePVgnOO5A7XVny1MikE6qng&callback=initMap">
        </script>

        <div class="row">
            <div class="col-md-4 text-center" style="color: deepskyblue">
                <h3>Reach Us</h3>
                <div class="text-center" style="color: whitesmoke">
                    <dl>
                        <dt>Address</dt>
                        <dd>Ward No-15</dd>
                        <dd>Hospital Road</dd>
                        <dd>Distt.SriGanganagar</dd>
                    </dl>
                </div>

            </div>
            <div class="col-md-4 text-center" style="color: deepskyblue">
                <h3>General</h3>
                <div class="text-center" style="color: whitesmoke">
                    <dl>
                        <dt>Contact Details</dt>
                           <dd>Harvinder Singh</dd>
                           <dd>9660147431</dd>
                           <dd>Arsh Kanwal Sodhi</dd>
                           <dd>7688812777</dd>
                           <dd>meetkanwalsodhi@gmail.com</dd>
                    </dl>


                </div>
            </div>
            <div class="col-md-4 text-center" style="color: deepskyblue">
                <h3>Any Query</h3>
                <form role="form">
                    <div class="form-group">
                        <input type="text"class="form-control"placeholder="Name">
                    </div>
                     <div class="form-group">
                        <input type="email"class="form-control"placeholder="Email">
                    </div>
                     <div class="form-group">
                        <input type="text"class="form-control"placeholder="Message">
                    </div>
                </form>


                <button type="button submit"class="btn btn-primary right-block">Submit</button>


            </div>
        </div>
    </div>
{% endblock %}

</body>

templates/garments/detail.html
{% extends 'garments/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ all_garments.product_name }}{% endblock %}</title>
</head>
<body>
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="{{ all_garments.product_image.url }}" class="img-responsive" width="480px" height="640px">
            </div>
            <div class="col-md-6" style="color: whitesmoke"><br><br>
                <h4><b>Product name : {{ all_garments.product_name }}</b></h4>
                <h4>Product price : {{ all_garments.product_price }}</h4>
                <h4>Product Details : {{ all_garments.product_details }}</h4>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>0

templates/garments/gallery.html
{% extends 'garments/base.html' %}

<head>
    <meta charset="UTF-8">

         <title>{% block title %} Garments {% endblock %}</title>



</head>
<body>
{% block body %}
    <div class="row">

        {% for garment in all_garments %}

            <div class="col-sm-4 col-lg-2">
                <div class="thumbnail">
                    <div class="product-thumb">
                        <img src="{{ garment.product_image.url }}" class="img-responsive" width="180px" height="240px">
                    </div>
                    <div class="text-center">

                        <h4 class="product-product" style="padding: 2px">
                            <b>{{ garment.product_name }}</b>
                        </h4>
                    </div>
                    <!-- View Details -->
                    <a href="{% url 'garments:detail' garment.id %}" class="btn btn-primary btn-sm center-block"
                       role="button">View Details</a>
                </div>
            </div>
        {% endfor %}

    </div>

{% endblock %}


</body>
</html>

templates/garments/index.html
{% extends 'garments/base.html' %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Aman Cloth House{% endblock %}</title>
</head>

{% block body %}
    <div class="container-fluid">
        <div class="thumbnail text-center" style="background: black ;padding-right :20px;">
            <img src="{% static "garments/images/home_image.jpg" %}" class="img-responsive text-center" width="100%"
                 height="400px">
            <div class="caption" style="color: greenyellow">
                <h2><i><b>Wear a Style..Wear a Smile!!</b></i></h2>
            </div>
        </div>
     </div>
        <div class="container" style="padding-right: 40px;padding-left: 40px;">
        <div style="color: darkgoldenrod; padding-left: 40px">
        <h3>Popular Women Products </h3></div>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
{#  <ol class="carousel-indicators">#}
{#    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>#}
{#    <li data-target="#myCarousel" data-slide-to="1" ></li>#}
{#    <li data-target="#myCarousel" data-slide-to="2"></li>#}
{#    <li data-target="#myCarousel" data-slide-to="3"></li>#}
{#  </ol>#}

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox" style="padding-left: 120px">
      <div class="item active">
         <div class="col-sm-4 col-lg-2">
             <a href="{% url 'garments:detail' 1 %}">
             <img src="{% static "garments/images/s7.jpg" %}" width="150px" height="150px" >
             </a>

        </div>
{#
         <div class="col-sm-4 col-lg-2">
              <a href="{% url 'garments:detail' 2 %}">
             <img src="{% static "garments/images/s8.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
             <a href="{% url 'garments:detail' 3 %}">
             <img src="{% static "garments/images/s6.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
              <a href="{% url 'garments:detail' 4 %}">
             <img src="{% static "garments/images/w4.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
             <a href="{% url 'garments:detail' 5 %}">
             <img src="{% static "garments/images/s4.jpg" %}" width="150px" height="150px" >
             </a>
        </div>

    </div>

    <div class="item">
            <div class="col-sm-4 col-lg-2">
              <a href="{% url 'garments:detail' 6 %}">
             <img src="{% static "garments/images/s3.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
             <a href="{% url 'garments:detail' 7 %}">
             <img src="{% static "garments/images/s2.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
            <a href="{% url 'garments:detail' 8 %}">
             <img src="{% static "garments/images/w1.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
             <a href="{% url 'garments:detail' 9 %}">
             <img src="{% static "garments/images/x3.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
             <a href="{% url 'garments:detail' 10 %}">
             <img src="{% static "garments/images/x4.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
    </div>


  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>
        <div style="color: darkgoldenrod; padding-left: 40px">
            <h3>Popular Men Products</h3></div>
    <div id="myCarousel4" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
{#  <ol class="carousel-indicators">#}
{#    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>#}
{#    <li data-target="#myCarousel" data-slide-to="1" ></li>#}
{#    <li data-target="#myCarousel" data-slide-to="2"></li>#}
{#    <li data-target="#myCarousel" data-slide-to="3"></li>#}
{#  </ol>#}

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox" style="padding-left: 120px">
    <div class="item active">
         <div class="col-sm-4 col-lg-2">
             <a href="{% url 'garments:detail' 19 %}">
             <img src="{% static "garments/images/y1.jpg" %}" width="150px" height="150px" >
             </a>
         </div>
         <div class="col-sm-4 col-lg-2">
             <a href="{% url 'garments:detail' 20 %}">
             <img src="{% static "garments/images/y2.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
              <a href="{% url 'garments:detail' 29 %}">
             <img src="{% static "garments/images/y11.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
              <a href="{% url 'garments:detail' 22 %}">
             <img src="{% static "garments/images/y4.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
              <a href="{% url 'garments:detail' 23 %}">
             <img src="{% static "garments/images/y5.jpg" %}" width="150px" height="150px" >
             </a>
        </div>

    </div>

    <div class="item">
            <div class="col-sm-4 col-lg-2">
              <a href="{% url 'garments:detail' 24 %}">
             <img src="{% static "garments/images/y6.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
              <a href="{% url 'garments:detail' 25 %}">
             <img src="{% static "garments/images/y7.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
             <a href="{% url 'garments:detail' 26 %}">
             <img src="{% static "garments/images/y8.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
              <a href="{% url 'garments:detail' 27 %}">
             <img src="{% static "garments/images/y9.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
         <div class="col-sm-4 col-lg-2">
             <a href="{% url 'garments:detail' 28 %}">
             <img src="{% static "garments/images/y10.jpg" %}" width="150px" height="150px" >
             </a>
        </div>
    </div>


  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel4" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel4" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>
    </div>

    <div style="padding: 50px"></div>

{% endblock %}